"""Promotion gate for causal graph expansion candidates.

This module creates merge recommendations for the core graph, but never mutates
the core graph directly.
"""

from __future__ import annotations

from typing import Any


PROMOTION_THRESHOLDS = {
    "min_confidence": 0.80,
    "min_seen_count": 3,
    "min_graph_support": 0.65,
    "min_data_coverage": 0.75,
}


class CausalPromotionGate:
    def evaluate(self, candidate: dict[str, Any]) -> dict[str, Any]:
        scores = candidate.get("scores") or {}
        confidence = float(candidate.get("overall_confidence") or 0)
        seen_count = int(candidate.get("seen_count") or 0)
        graph_support = float(scores.get("graph_support") or 0)
        data_coverage = float(scores.get("data_coverage") or 0)
        falsification = candidate.get("falsification") or []
        review_status = candidate.get("review_status") or candidate.get("graph_status") or candidate.get("decision")
        cause = candidate.get("cause_node")
        effect = candidate.get("effect_node")

        checks = [
            self._check("manual_review", review_status == "eligible_for_promotion", f"review_status={review_status}"),
            self._check("confidence", confidence >= PROMOTION_THRESHOLDS["min_confidence"], f"{confidence:.2f} >= {PROMOTION_THRESHOLDS['min_confidence']:.2f}"),
            self._check("repeat_observation", seen_count >= PROMOTION_THRESHOLDS["min_seen_count"], f"{seen_count} >= {PROMOTION_THRESHOLDS['min_seen_count']}"),
            self._check("graph_support", graph_support >= PROMOTION_THRESHOLDS["min_graph_support"], f"{graph_support:.2f} >= {PROMOTION_THRESHOLDS['min_graph_support']:.2f}"),
            self._check("data_coverage", data_coverage >= PROMOTION_THRESHOLDS["min_data_coverage"], f"{data_coverage:.2f} >= {PROMOTION_THRESHOLDS['min_data_coverage']:.2f}"),
            self._check("falsifiability", len(falsification) > 0, f"{len(falsification)} falsification tests"),
            self._check("node_mapping", bool(cause and effect), f"{cause or 'missing'} -> {effect or 'missing'}"),
        ]
        eligible = all(c["passed"] for c in checks)

        return {
            "candidate_id": candidate.get("candidate_id") or candidate.get("id"),
            "eligible": eligible,
            "recommended_action": "create_core_edge_pr" if eligible else "continue_watchlist",
            "checks": checks,
            "proposed_core_edge": self._proposed_edge(candidate) if eligible else None,
            "blocked_reasons": [c["name"] for c in checks if not c["passed"]],
        }

    @staticmethod
    def _check(name: str, passed: bool, detail: str) -> dict[str, Any]:
        return {"name": name, "passed": bool(passed), "detail": detail}

    @staticmethod
    def _proposed_edge(candidate: dict[str, Any]) -> dict[str, Any]:
        return {
            "source_node": candidate.get("cause_node"),
            "target_node": candidate.get("effect_node"),
            "mechanism_description": candidate.get("mechanism"),
            "evidence_type": "ai_assisted_governed_candidate",
            "initial_confidence": round(float(candidate.get("overall_confidence") or 0), 4),
            "promotion_note": (
                "Generated by promotion gate. Requires code review and human approval "
                "before adding to INITIAL_EDGES/Core Graph."
            ),
        }
