const domainTextZh: Record<string, string> = {
  // Core themes
  'AI Capex / Tech Concentration': 'AI 资本开支 / 科技集中度',
  'Dollar Liquidity / Funding Squeeze': '美元流动性 / 融资挤压',
  'Global Credit / Default Cycle': '全球信用 / 违约周期',
  'Japan Carry / Yen Reversal': '日本套息 / 日元反转',
  'China / Asia Spillover': '中国 / 亚洲外溢',
  'Europe Sovereign / Credit Contagion': '欧洲主权 / 信用传染',
  'Commodity / Energy Shock': '商品 / 能源冲击',
  'Tracks whether AI investment, semiconductor momentum, mega-cap concentration, and related credit proxies are becoming a systemic risk focus.': '跟踪 AI 投资、半导体动量、巨头集中度和相关信用代理指标是否正在形成系统性风险主线。',
  'Tracks broad dollar strength, US rates, repo funding, and EM FX sensitivity.': '跟踪美元强势、美国利率、回购融资和新兴市场汇率敏感性。',
  'Tracks corporate credit spreads, loan delinquency, bank funding, and downgrade/default pressure.': '跟踪企业信用利差、贷款逾期、银行融资和降级/违约压力。',
  'Tracks yen depreciation pressure, Japan equity sensitivity, volatility, and carry-unwind risk.': '跟踪日元贬值压力、日本股市敏感性、波动率和套息平仓风险。',
  'Tracks China credit impulse proxies, CNY pressure, Hong Kong equities, Korea equities, and trade spillover.': '跟踪中国信用脉冲代理、人民币压力、港股、韩股和贸易外溢。',
  'Tracks Eurozone credit, Italy stress proxies, EUR/USD, European equities, and sovereign-bank feedback.': '跟踪欧元区信用、意大利压力代理、欧元兑美元、欧洲股市和主权-银行反馈。',
  'Tracks oil, gas, food, metals, gold, and the inflation-growth squeeze from supply shocks.': '跟踪油气、食品、金属、黄金以及供给冲击带来的通胀-增长挤压。',
  'Identifies when a popular growth narrative is masking concentration, credit, or supply-chain fragility.': '识别热门成长叙事是否掩盖了集中度、信用或供应链脆弱性。',
  'Explains when tightening dollar funding can transmit from rates into FX, credit, and EM assets.': '解释美元融资收紧如何从利率传导到汇率、信用和新兴市场资产。',
  'Turns a broad credit warning into traceable funding, downgrade, and default-cycle evidence.': '把宽泛的信用预警拆解成可追踪的融资、降级和违约周期证据。',
  'Surfaces risk when yen weakness looks supportive for equities but increases reversal and intervention risk.': '识别日元走弱看似支撑股市、但同时提升反转和干预风险的状态。',
  'Connects China-specific stress to Asian equity, FX, and trade-dependency transmission.': '把中国特定压力连接到亚洲股市、汇率和贸易依赖传导。',
  'Makes European sovereign, credit, and FX feedback loops visible before they dominate headlines.': '在欧洲主权、信用和汇率反馈成为头条前，将其传导链可视化。',
  'Separates growth-sensitive commodities from inflationary supply shocks and safe-haven demand.': '区分增长敏感型商品、通胀型供给冲击和避险需求。',

  // Status / evidence
  critical: '严重',
  priority: '优先',
  watch: '观察',
  background: '背景',
  ok: '正常',
  error: '异常',
  validated: '已验证',
  promotion_ready: '可升级',
  candidate_graph: '候选图谱',
  watchlist: '观察清单',
  weak: '弱证据',
  rejected: '已拒绝',
  eligible_for_promotion: '可升级',
  manual_review: '人工审核',
  confidence: '置信度',
  repeat_observation: '重复观测',
  graph_support: '图谱支持',
  data_coverage: '数据覆盖',
  falsifiability: '可证伪性',
  node_mapping: '节点映射',
  node: '指标',
  chain: '传导链',
  sub_index: '子指数',
  institutional_radar: '机构雷达',
  hidden_risk: '隐藏风险',

  // Watch metrics
  'AI/Cloud capex basket': 'AI/云资本开支篮子',
  SOX: '半导体指数',
  'DRAM/NAND producer basket': 'DRAM/NAND 生产商篮子',
  'AI/cloud credit proxy': 'AI/云信用代理',
  'SPX breadth': '标普500市场广度',
  DXY: '美元指数',
  'US 10Y': '美国10年期国债',
  'SOFR-EFFR spread': 'SOFR-EFFR 利差',
  'KRW/USD': '韩元兑美元',
  'EM bonds': '新兴市场债券',
  'HY OAS': '高收益债利差',
  'BBB OAS': 'BBB 信用利差',
  'BAA-10Y spread': 'BAA-10Y 利差',
  'loan delinquency': '贷款逾期率',
  'regional banks': '区域银行',
  'USD/JPY': '美元兑日元',
  Nikkei: '日经指数',
  VIX: 'VIX 波动率',
  'US-Japan rate differential': '美日利差',
  'carry positioning': '套息交易仓位',
  'China social finance': '中国社融',
  'CNY/USD': '人民币兑美元',
  'Hang Seng': '恒生指数',
  KOSPI: '韩国 KOSPI',
  'Korea current account': '韩国经常账户',
  'Euro HY OAS': '欧洲高收益债利差',
  'Italy risk proxy': '意大利风险代理',
  'EUR/USD': '欧元兑美元',
  'Euro Stoxx 50': '欧洲斯托克50',
  WTI: 'WTI 原油',
  'natural gas': '天然气',
  wheat: '小麦',
  copper: '铜',
  gold: '黄金',
  shipping: '航运',

  // Commercial readiness
  'Ready for paid pilot conversations; continue hardening data depth, RBAC, and report approval workflow.': '已具备付费试点沟通基础；后续继续强化数据深度、权限体系和报告审批流程。',
  'Evidence table, falsification section, source links, and compliance footer.': '包含证据表、证伪条件、来源链接和合规声明。',
  'Show enough evidence to build trust; reserve full causal chains, institutional radar depth, exports, and watch automation for paid tiers.': '免费层展示足够证据建立信任；完整因果链、机构雷达深度、导出和自动关注留给付费层。',
  'Single-node Docker Compose': '单机 Docker Compose 部署',
  'Private LAN deployment': '内网私有化部署',
  'White-label frontend': '白标前端',
  'Managed API integration': '托管 API 集成',
  'Pilot / internal demo': '试点 / 内部演示',
  'Broker research or advisor desk': '券商研究或投顾中台',
  'Client-facing broker app': '面向客户的券商 App',
  'Institutional internal systems': '机构内部系统',
  ready: '已就绪',
  ready_with_env_config: '配置环境后可交付',
  design_ready: '设计已就绪',
  api_ready: 'API 已就绪',
  'Executive Summary': '执行摘要',
  'What Changed': '发生了什么变化',
  'Core Theme': '核心主题',
  'Official Institutional Radar': '官方机构雷达',
  'What Would Invalidate This View': '什么会推翻当前判断',
  'AI earnings narrative suppressing equity damage': 'AI 盈利叙事抑制股市损害显现',
  'Semiconductor cycle supporting Korea equities despite FX fragility': '半导体周期在汇率脆弱下支撑韩国股市',
  'Weak yen buffering Japanese equity damage': '弱日元缓冲日本股市损害',
  'Policy easing expectations suppressing credit damage': '政策宽松预期抑制信用损害显现',
  'Passive and concentration flows delaying visible equity damage': '被动资金与集中度延迟股市损害显现',
  'AI capex expectations and mega-cap earnings revisions can support index-level equity prices even while concentration risk rises.': 'AI 资本开支预期和大型科技股盈利修正，可能在集中度风险上升时继续支撑指数。',
  'Global semiconductor strength can support Korean equities while KRW pressure signals external fragility.': '全球半导体强势可能支撑韩国股市，但韩元压力提示外部脆弱性仍在。',
  'Yen depreciation supports exporter earnings and can keep Nikkei resilient, while increasing intervention and carry-trade reversal risk.': '日元贬值支撑出口企业盈利并维持日经韧性，但同时增加干预和套息交易反转风险。',
  'Rate-cut or liquidity-support expectations can keep credit damage from materializing even when underlying pressure is elevated.': '即使底层压力较高，降息或流动性支持预期也可能暂时阻止信用损害显现。',
  'Index concentration and passive flows can mask deterioration under the surface until breadth, earnings, or liquidity breaks.': '指数集中度和被动资金流可能掩盖底层恶化，直到市场广度、盈利或流动性转弱。',
  'Strong candidate, but still requires repeated validation and human approval.': '强候选机制，但仍需要重复验证和人工批准。',
  'Candidate is structurally plausible but weakly supported by the current graph.': '候选机制在结构上合理，但当前图谱支持较弱。',
  'Candidate needs better measurable indicators before promotion.': '升级前需要更好的可量化指标支持。',
  'Candidate is suitable for watchlist or candidate graph validation.': '适合进入观察清单或候选图谱继续验证。',
  'Explain why hidden pressure is high while realized damage remains low, and propose candidate causal graph expansions.': '解释为什么隐藏压力较高但实际损害仍低，并提出候选因果图扩展。',
  'No direct mutation of the core graph.': '不得直接修改核心图谱。',
  'Every mechanism must include falsification tests.': '每个机制都必须包含证伪测试。',
  'Prefer measurable variables and existing node IDs.': '优先使用可观测变量和现有节点 ID。',
  'Separate pressure suppression from realized damage.': '区分压力被抑制和实际损害已经发生。',
  'Free': '免费版',
  'Pro': '专业版',
  'Institutional': '机构版',
}

export function localizeDomainText(value: unknown, lang: 'zh' | 'en'): string {
  if (value === null || value === undefined) return ''
  const text = String(value)
  if (lang !== 'zh') return text
  if (domainTextZh[text]) return domainTextZh[text]
  return text
}

export function localizeDomainList(values: unknown[] | undefined, lang: 'zh' | 'en'): string[] {
  return (values || []).map((value) => localizeDomainText(value, lang))
}
